SET(ARCH_OBJECTS
  # exceptions.asm
)

SET(ARCH_SOURCES
  cpu.cpp
  paging.cpp
  syscall_entry.cpp
  timer.cpp
)

ENABLE_LANGUAGE(ASM)

SET_SOURCE_FILES_PROPERTIES(
  ${ARCH_OBJECTS} PROPERTIES COMPILE_FLAGS "-x assembler-with-cpp"
)

ADD_LIBRARY(arch STATIC ${ARCH_SOURCES} ${ARCH_OBJECTS})

SET_TARGET_PROPERTIES(arch PROPERTIES LINKER_LANGUAGE CXX)

INSTALL(TARGETS arch DESTINATION lib)
